version: "3"

services:
  task-tracker-db:
    image: postgres:15
    container_name: task-tracker-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./task_tracker_db:/var/lib/postgresql/data
    networks:
      - task-tracker-network

networks:
  task-tracker-network:
    driver: bridge
